name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ────────────────────────────────
  # 1. GỌI API & XỬ LÝ HTTP
  # ────────────────────────────────
  http: ^1.2.2
  mime: ^1.0.5
  http_parser: ^4.0.2

  # ────────────────────────────────
  # 2. LƯU TRỮ & XÁC THỰC
  # ────────────────────────────────
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # ────────────────────────────────
  # 3. GIAO DIỆN & HÌNH ẢNH
  # ────────────────────────────────
  google_fonts: ^6.3.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # ────────────────────────────────
  # 4. QUẢN LÝ TRẠNG THÁI
  # ────────────────────────────────
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.2

  # ────────────────────────────────
  # 5. HỖ TRỢ THANH TOÁN & DEEP LINK
  # ────────────────────────────────
  url_launcher: ^6.2.6
  app_links: ^3.5.1
  flutter_zalopay_sdk:

  # ────────────────────────────────
  # 6. CHIA SẺ & LƯU QR
  # ────────────────────────────────
  share_plus: ^7.2.2
  path_provider: ^2.1.2

  # ────────────────────────────────
  # 7. DEBUG & LOGGING
  # ────────────────────────────────
  logger: ^1.1.0

  # ────────────────────────────────
  # 8. THÔNG BÁO TRONG APP & BADGE + NHẮC NHỞ XE CHẠY
  # ────────────────────────────────
  badges: ^3.1.2
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.9.0+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  timezone: ^0.9.4                              
  flutter_dotenv: ^6.0.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/default.png
    - assets/images/bus_logo.png
    - assets/images/google_logo.png
    - assets/images/vungtau.png
    - assets/images/dalat.png
    - assets/images/sapa.png
    